services:
  inference:
    image: apnea-inference:0.1
    container_name: apnea_inference
    build:
      context: ./inference
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: /models/model_int8.tflite
      DATA_DIR: /data/apnea-ecg
      PATIENTS_DIR: /patients
      RECORDING_FS: 100
    volumes:
      - ./results:/models
      - ./data/apnea-ecg:/data/apnea-ecg
      - ./inference/data/patients:/patients
