services:
  inference:
    image: apnea-inference:0.1
    container_name: apnea_inference
    build:
      context: ./inference
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./inference/data/models:/models
      - ./data/apnea-ecg:/data/apnea-ecg
      - ./inference/data/patients:/patients
      - analyses:/analyses

volumes:
  analyses:
